### ISSUE TITLE
Errors on TigrisToggle

### ISSUE THREAD

**Issue by faceleg** [billyvg/tigris.nvim#2]
```
Error detected while processing function remote#define#FunctionBootstrap[6]..remote#define#FunctionOnChannel:
line   10:
E746: Function name does not match script file name: tigris#highlight#clear
Error detected while processing function tigris#toggle[1]..tigris#disable:
line    1:
E117: Unknown function: tigris#highlight#clear
E488: Trailing characters
Press ENTER or type command to continue
```

Installed with:

```
call dein#add('neovim/node-host', { 'build': 'npm install', 'merged': 0 })
call dein#add('billyvg/tigris.nvim', { 'build': './install.sh' })
```

**Comment by mhartington** [comment]
Seeing this as well, seems that any built in Vim functions are only being half recognized by neovim.

**Comment by billyvg** [comment]
Please update the plugin and try again, all of the vim commands are now fixed (884712ac9493c3c14775d9857e7d1037d98555c1, abe87f8010e6b2f9d2aae8835e91acc02f46adbd)

Edit: parsing on buffer enter doesn't seem to be working, so you'll have to run `:TigrisStart` for now

**Comment by mhartington** [comment]
Hmm, I'm still getting an error. Still the same install as @faceleg but getting this error

```
"test.js" 38L, 734C
remote/host: node host registered plugins ['tigris.js']
remote/host: python3 host registered plugins ['denite', 'deoplete']
remote/host: generated the manifest file in "/Users/mhartington/.config/nvim/.init.vim-rplugin~"
E117: Unknown function: _tigris_enable
```

**Comment by billyvg** [comment]
@mhartington Try restarting Neovim after running `:UpdateRemotePlugins` since the remote plugin gets cached.

**Comment by mhartington** [comment]
Ahh, what a derp moment. Yep! Looks like it working now. Thanks

**Comment by billyvg** [comment]
No worries, I've spent more time than I care to admit trying to get this to work while developing it.
